import Foundation

enum GAppAnalyticActions: String {
    
    static var delaySliderInterval: TimeInterval = 1.0
    
    case privacy = "privacy"
    case terms = "terms"
    case restore = "restore"
    case purchase = "purchase"
    case haptic = "haptic"
    case darkMode = "dark_mode"
    case faq = "faq"
    case ourWebsite = "our_website"
    case manageSubscriptions = "manage_subscriptions"
    case cancelSubscription = "cancel_subscription"
    // Version 2
    //    case v2FirstLaunch = "v2_first_launch"
    //    case v2AppOpen = "v2_app_open"
    
    case v2Onboarding = "v2_onboarding_screen"
    case v2TabBar = "v2_tab_bar_screen"
    case v2Paywall = "v2_paywall_screen"
    case v2BPaywall = "v2_paywall_screen_B"
    case v2CatchUp = "v2_catch_up_screen"
    case v2MicrophoneReminder = "v2_microphone_reminder_screen"
    case v2HeadphonesReminder = "v2_headphones_reminder_screen"
    case v2VoiceRecordingReminder = "v2_voice_recording_reminder_screen"
    case v2HearingScreen = "v2_hearing_screen"
    case v2TranscribeScreen = "v2_transcribe_screen"
    case v2SettingsScreen = "v2_settings_screen"
    case v2HearingProSetupScreen = "v2_hearing_pro_setup_screen"
    case v2TemplatesScreen = "v2_templates_screen"
    case v2CompressorScreen = "v2_compressor_screen"
    case v2VoiceChangerScreen = "v2_voice_changer_screen"
    case v2LimiterScreen = "v2_limiter_screen"
    case v2EqualizerScreen = "v2_equalizer_screen"
    case v2MoreScreen = "v2_more_screen"
    case v2TranscribeMainScreen = "v2_transcribe_main_screen"
    case v2TranslateScreen = "v2_translate_screen"
    case v2TypeScreen = "v2_type_screen"
    case v2SavedTranscriptsScreen = "v2_saved_transcripts_screen"
    case v2TranscriptDetailsScreen = "v2_transcript_details_screen"
    case v2TranscribeTextSetupScreen = "v2_transcribe_text_setup_screen"
    case v2TranslateTextSetupScreen = "v2_translate_text_setup_screen"
    case v2TranslateLanguageSetupScreen = "v2_translate_language_setup_screen"
    case v2TranscribeLanguagesScreen = "v2_transcribe_languages_screen"
    case v2TranslateToLanguagesScreen = "v2_translate_to_languages_screen"
    case v2TranslateFromLanguagesScreen = "v2_translate_from_languages_screen"
    case v2PreOnboardingScreen = "v2_pre_onboarding_screen"
    case v2EmailScreen = "v2_email_screen"
    case v2PermissionsScreen = "v2_permissions_screen"
    case v2CrossPromoScreen = "v2_cross_promo_screen"
    
    case hearing = "hearing"
    case transcribe = "transcribe"
    //    case settings = "settings"
    
    case v2AppStoreEvent = "v2_app_store_event"
    case v2AppStore = "v2_app_store"
    case v2Notification = "v2_notification"
    case v2Deeplink = "v2_deeplink"
    
    
    case openFromHearing = "open_from_hearing"
    case openFromTranscribe = "open_from_transcribe"
    case openFromSetting = "open_from_settings"
    case openFromLaunch = "open_from_launch"
    case openFromAppStore = "open_from_app_store"
    case openFromNotification = "open_from_notification"
    case openFromDeeplink = "open_from_deeplink"
    case openAfterOnboarding = "open_after_onboarding"
    
    // Additional actions
    case trial = "trial"
    case event = "event"
    case action = "action"
    case open = "open"
    case close = "close"
    case autoClose = "auto_close"
    case enable = "enable"
    case disable = "disable"
    case allow = "allow"
    case airPlay = "air_play"
    case connected = "connected"
    case changeAppIcon = "change_app_icon"
    case support = "support"
    case more = "more"
    case info = "info"
    case select = "select"
    case subscribe = "subscribe"
    case microphone = "microphone"
    case change = "change"
    case share = "share"
    case redeem = "redeem"
    case search = "search"
    case rate = "rate"
    case compliant = "compliant"
    
    case green = "green"
    case orange = "orange"
    case red = "red"
    case blue = "blue"
    case violet = "violet"
    case lightBlue = "light_blue"
    case gradientOrange = "gradient_orange"
    
    case after = "after"
    case before = "before"
    case `continue` = "continue"
    
    case proSetup = "pro_setup"
    case noise = "noise"
    case stereo = "stereo"
    case templates = "templates"
    case changeBalance = "change_balance"
    case changeVolume = "change_volume"
    
    case reset = "reset"
    case musicMode = "music_mode"
    case systemVolume = "system_volume"
    case clearVoice = "clear_voice"
    case voiceChanger = "voice_changer"
    case changeMicrophone = "change_microphone"
    case changeMainScreen = "change_main_screen"
    case changeTemplate = "change_template"
    case compressor = "compressor"
    case limiter = "limiter"
    case equalizer = "equalizer"
    case shakeClearText = "shake_clear_text"
    case offlineTranslate = "offline_translate"
    case flip = "flip"
    case clearText = "clear_text"
    case keyboardClearText = "keyboard_clear_text"
    case keyboardCopyAllText = "keyboard_copy_all_text"
    case saveText = "save_text"
    case keyboardSaveText = "keyboard_save_text"
    case keyboardDone = "keyboard_done"
    
    case type = "type"
//    case saved = "saved"
    case textSetup = "text_setup"
    case languageSetup = "language_setup"
    case expand = "expand"
    case transcript = "transcript"
    case delete = "delete"
    case changeLanguage = "change_language"
    case downloadLanguage = "download_language"
    case translateLanguage = "translate_language"
    case userLanguage = "user_language"
    case translate = "translate"
   
    
    case translateMode = "translate_mode"
    case rotate = "rotate"
    case fullScreen = "full_screen"
    case alignment = "alignment"
    case weight = "weight"
    case changeFontSize = "change_font_size"
    case listening = "listening"
    
    // New UI
    
    case appLaunched = "app_launched"
    case appClosed = "app_closed"
    case firstOpenApp = "first_open_app"
    
    case paywallSeen = "paywall_seen"
    case paywallPassed = "paywall_passed"
    case purchaseCheckout = "purchase_checkout"
    case purchaseActivate = "purchase_activate"
    
    case obSeen = "ob_seen"
    case obPassed = "ob_passed"
    
    case headphonesConnected = "headphones_connected"
    case hearingActivated = "hearing_activated"
    case hearingDeactivated = "hearing_deactivated"
    
    case homeOptionsActivated = "home_options_activated"
    case homeOptionsDeactivated = "home_options_deactivated"
    case volumeBarMoved = "volume_bar_moved"
    case stringMoved = "string_moved"
    case templatesOptionActivated = "templates_option_activated"
    case templatesOptionDeactivated = "templates_option_deactivated"
    case setupOptionActivated = "setup_option_activated"
    case setupOptionDeactivated = "setup_option_deactivated"
    case mainScreenOpened = "main_screen_opened"
    case infoTooltipOpened = "info_tooltip_opened"
    case hapticFeedback = "haptic_feedback"
    case shakeDeleteTranscript = "shake_delete_transcript"
    case settingsClicked = "settings_clicked"
    case savingOpened = "saving_opened"
    case typeScreenOpened = "type_screen_opened"
    case typeScreenClosed = "type_screen_closed"
    case typeAreaExpanded = "type_area_expanded"
    case translateActivated = "translate_activated"
    case translateDeactivated = "translate_deactivated"
    case transcribeActivated = "transcribe_activated"
    case transcribeDeactivated = "transcribe_deactivated"
    case screenFlipped = "screen_flipped"
    case deleted = "deleted"
    case saved = "saved"
    case sharedResult = "shared_result"
    case permissionViewed = "permission_viewed"
    case permissionGranted = "permission_granted"
    case pushOpened = "push_opened"
    
    // Source
    case source = "source"
    case sourceDefault = "default"
    case sourceOb = "ob"
    case sourceAppLaunch = "app_launch"
    case sourceAfterPwOb = "after_pw_ob"
    case sourceVolumeBar = "volume_bar"
    case sourceSetupBtn = "setup_btn"
    case sourceTemplatesBtn = "templates_btn"
    case sourceActivateBtn = "activate_btn"
    case sourceNonoiseBtn = "nonoise_btn"
    case sourceStereoBtn = "stereo_btn"
    case sourceLeftRightString = "left_right_string"
    case sourceTranscriptMain = "transcript_main"
    case sourceAfterPwlTranscript = "after_pwl_transcript"
    case sourceSettings = "settings"
    case sourceTranscribeBtn = "transcribe_btn"
    case sourceTranslateBtn = "translate_btn"
    case sourceTypeBtn = "type_btn"
    case sourceAfterPw = "after_pw"
    case sourceHearingActivateBtn = "hearing_activate_btn"
    case sourceHeader = "header"
    
    // Status
    case statusTrue = "true"
    case statusFalse = "false"
    
    //
    
    case hearingMain = "hearing_main"
    case transcriptionMain = "transcription_main"
    case settingsMain = "settings_main"
}
